title: Welcome to Kristen's Blog
author: Kristen Lee
email: klee2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  

# social links
instagram_username: kristen.llee
github_username:  7kristenlee


show_excerpts: true # set to false to remove excerpts on the homepage

#theme: jekyll-agency
remote_theme: 7kristenlee/agency

