title: Welcome to Kristen's Blog
author: Kristen Lee
email: klee2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  this includes my Brag Sheet and Social Media

# social links
instagram_username: kristen.llee
github_username:  7kristenlee

links:
 label: Instagram
 url: "https://www.instagram.com/kristen.llee/"


show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-merlot
